// display-names.ts — subcategory id -> short display name for board tiles.
// VIEW-LAYER ONLY. Extracted from the briefs' subcategory headings
// (reference-model/*/BRIEF.md `### <ID> — <name>`, FIN `-- name --`, PEOPLE `name → ID`).
// Not a schema field; LINT-4 (exactly-10-fields) stays closed.

export const DISPLAY_NAMES: Record<string, string> = {
  "GTM-07": "ICP",
  "GTM-08": "Positioning thesis",
  "GTM-09": "Market sizing & competitive landscape",
  "GTM-10": "Marketing & demand assets",
  "GTM-11": "Pipeline system of record",
  "GTM-12": "Scheduling infrastructure",
  "GTM-13": "Sales motion & qualification",
  "GTM-14": "Pipeline review & forecast cadence",
  "GTM-15": "Talk track",
  "GTM-16": "Sales enablement collateral",
  "GTM-17": "Win/loss & churn-reason capture",
  "GTM-18": "Onboarding & success milestones",
  "GTM-19": "Support handling",
  "GTM-20": "Metrics definitions",
  "GTM-21": "KPI tracking",
  "GTM-22": "Segmented targets & funnel model",
  "PRODUCT-01": "Roadmap & Prioritization",
  "PRODUCT-02": "Specs & Product-Development Process",
  "PRODUCT-03": "User Research & Continuous Discovery",
  "PRODUCT-04": "Product-Market-Fit Evidence",
  "PRODUCT-05": "Product Metrics & Analytics",
  "PRODUCT-06": "Product Strategy & Defensibility",
  "OPS-01": "Ownership & accountability map (\"who owns what\") [Sprint-L prereq]",
  "OPS-02": "Management operating rhythm",
  "OPS-03": "Goal-setting & review cadence",
  "OPS-04": "Documented core processes [Sprint-L prereq]",
  "OPS-05": "Vendor & procurement management",
  "OPS-06": "Internal tooling, IT & access management",
  "OPS-07": "Project & change management",
  "OPS-08": "Physical operations",
  "OPS-09": "Quality management",
  "PEOPLE-01": "Talent acquisition & retention",
  "PEOPLE-02": "Total Rewards, compensation",
  "PEOPLE-03": "Onboarding",
  "PEOPLE-04": "Performance & feedback",
  "PEOPLE-05": "Org design / structure",
  "PEOPLE-06": "Culture",
  "PEOPLE-07": "Total Rewards, benefits",
  "PEOPLE-08": "Employee handbook / HR policy set",
  "LEGAL-01": "Entity, formation & good standing",
  "LEGAL-02": "Corporate action record",
  "LEGAL-03": "Financing closing sets",
  "LEGAL-04": "Securities-law compliance",
  "LEGAL-05": "IP legal paperwork",
  "LEGAL-06": "Employment & contractor legal paperwork",
  "LEGAL-07": "Executed contracts",
  "LEGAL-08": "Litigation, disputes & claims",
  "LEGAL-09": "Privacy & data protection",
  "LEGAL-10": "Website, accessibility & marketing compliance",
  "CAP-01": "Capital strategy & plan [Sprint-L prereq]",
  "CAP-02": "Cap table & securities record",
  "CAP-03": "Equity plan & grant administration",
  "CAP-04": "Valuation record",
  "CAP-05": "Financing instruments record",
  "CAP-06": "Fundraising motion & materials [Sprint-L prereq]",
  "CAP-07": "Investor relations & reporting [Sprint-L prereq]",
  "FIN-01": "Bookkeeping, close and the finance stack",
  "FIN-02": "Financial reporting and P&L analysis",
  "FIN-03": "Budget and financial plan",
  "FIN-04": "Financial model construction and maintenance",
  "FIN-05": "Treasury and cash management",
  "FIN-06": "Income and franchise tax: owned and current",
  "FIN-07": "Payroll, information returns and equity-exercise reporting: owned and",
  "FIN-08": "Sales-tax nexus: question answered, monitoring owned",
  "VIS-01": "Mission & enterprise identity \u00b7 authority-backed",
  "VIS-02": "Long-range positioning strategy \u00b7 authority-backed",
  "VIS-03": "Company-level goals (content) \u00b7 authority-backed",
  "ENG-01": "Architecture & technical decisions [authority-backed]",
  "ENG-02": "Code & development practice [authority-backed]",
  "ENG-03": "CI/CD & deploy (B-19 technical face) [authority-backed]",
  "ENG-04": "Reliability & incidents [authority-backed]",
  "ENG-05": "Product infrastructure (B-4 product side) [authority-backed]",
  "ENG-06": "Data & continuity [authority-backed]",
  "ENG-07": "Dependencies [authority-backed]",
  "ENG-08": "Knowledge transfer & developer docs [expert-authored",
  "AIOPS-01": "AI-use footprint & inventory",
  "AIOPS-02": "Communicated stance & governed use-in-workflow",
  "AIOPS-03": "Automation-in-operation",
  "AIOPS-04": "Working governance: data rules, decision ownership, intake record",
  "AIOPS-05": "Outcome awareness (INFORMATIONAL; ruled R-3, B-20 pattern; expert-authored",
  "COMP-01": "Security assurance & certification posture",
  "COMP-02": "Corporate risk insurance",
  "COMP-03": "Vendor security-risk posture / TPRM (authority-backed;",
};
